export const selectActiveStep  = (state) => state.stepInfo.activeStep
export const selectPlainText = (state) => state.stepInfo.plainText
export const selectMatrixColsLen = (state) => state.stepInfo.matrixInfo.colsLen
export const selectMatrixRowsLen = (state) => state.stepInfo.matrixInfo.rowsLen
export const selectCurrentStep = (state) => state.stepInfo.currentStep
export const selectKeyRaw = (state) => state.stepInfo.keyRaw
export const selectStepChange = (state) => state.stepInfo.stepChange
export const selectHighlightStep = (state) => state.stepInfo.highlightStep
export const selectHexText = (state) => state.stepInfo.hexText
export const selectShowHex = (state) => state.stepInfo.showHex