export const selectActiveStep  = (state) => state.stepInfo.activeStep
export const selectPlainText = (state) => state.stepInfo.plainText
export const selectRowKey = (state) => state.stepInfo.rowKey
export const selectColumnKey = (state) => state.stepInfo.columnKey
export const selectNextSubstepSignal = (state) => state.stepInfo.nextSubstepSignal
export const selectRowsInfo = (state) => state.stepInfo.rowsInfo
export const selectColumnsInfo = (state) => state.stepInfo.columnsInfo
export const selectRowsCurrentStep = (state) => state.stepInfo.rowsInfo.currentStep
export const selectRowsSubsteps = (state) => state.stepInfo.rowsInfo.substeps
export const selectColumnsCurrentStep = (state) => state.stepInfo.columnsInfo.currentStep
export const selectColumnsSubsteps = (state) => state.stepInfo.columnsInfo.substeps
export const selectMatrixColsLen = (state) => state.stepInfo.matrixInfo.colsLen
export const selectMatrixRowsLen = (state) => state.stepInfo.matrixInfo.rowsLen
export const selectCurrentStep = (state) => state.stepInfo.currentStep
export const selectKeyRaw = (state) => state.stepInfo.keyRaw
export const selectStepChange = (state) => state.stepInfo.stepChange